{{#if useAppDockerfile}}
FROM ruby:3.2-slim

RUN apt-get update -qq && apt-get install --no-install-recommends -y \
  build-essential{{#if dbPostgres}} libpq-dev{{/if}}{{#if dbMysql}} default-libmysqlclient-dev{{/if}} \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY Gemfile Gemfile.lock ./
RUN bundle install --without development test

COPY . .

EXPOSE 3000

CMD ["bundle", "exec", "puma", "-C", "config/puma.rb"]
{{/if}}
