.PHONY: build run dev
build:
	cargo build --release

run:
	cargo run

dev:
	cargo watch -x run

{{#if useTests}}
.PHONY: test test-cover
test:
	cargo test

test-cover:
	cargo tarpaulin --out Html --output-dir coverage
{{/if}}

{{#if useLint}}
.PHONY: lint fmt fmt-fix
lint:
	cargo clippy -- -D warnings

fmt:
	cargo fmt --all -- --check

fmt-fix:
	cargo fmt --all
{{/if}}

{{#if useDocker}}
.PHONY: infra-up infra-down
infra-up:
	docker compose up -d

infra-down:
	docker compose down
{{/if}}

{{#if ormDiesel}}
.PHONY: db-setup db-migrate db-generate
db-setup:
	diesel setup

db-migrate:
	diesel migration run

db-generate:
	diesel migration generate $(name)
{{/if}}

{{#if ormSqlx}}
.PHONY: db-create db-migrate db-prepare
db-create:
	cargo sqlx database create

db-migrate:
	cargo sqlx migrate run

db-prepare:
	cargo sqlx prepare --workspace
{{/if}}

{{#if ormSeaOrm}}
.PHONY: db-migrate
db-migrate:
	cargo run -- migrate
{{/if}}
