# ---- build stage ----
FROM golang:1.22-alpine AS build
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 go build -ldflags="-s -w" -o /app/bin/{{projectName}} ./cmd

# ---- runtime stage ----
FROM alpine:3.20 AS runtime
WORKDIR /app
RUN apk add --no-cache ca-certificates

COPY --from=build /app/bin/{{projectName}} /app/{{projectName}}

EXPOSE 8080
CMD ["/app/{{projectName}}"]
